### PR TITLE
Ba html bootstrap

### PR DESCRIPTION
**Pull request by bernardanderson**
Let me know if you see any issues!

### CODE REVIEW

**Comment by VikingPaul** [comment]
Since we'll be using the projector in class when we present and it has a horrible resolution, shouldn't the columns all be for the xs size?

**Comment by bernardanderson** [comment]
The use of md in the in messages seems to work better than the xs but I did change the others to xs.  For the checkboxes I added a dual "col" when dropping below 768 but read the latest detailed commit message for a unfixable error. I don't think that will be an issue as the resolution of the projector cannot be lower than 800x600 (my guess is its 1024x768).

**Comment by morecallan** [comment]
:+1: Looks awesome, Bernie. 
-One quick fix before merging: CSS line 6 needs # before hex-val.

**Comment by bernardanderson** [comment]
Nice catch!  I pushed the fix.

**Comment by VikingPaul** [comment]
:+1: looks good to me.

**Pull request merged**
